### ISSUE TITLE
Header file not found

### ISSUE THREAD

**Issue by lpugin** [Noroxs/VerovioExample#1]
When trying to build the example the `#import <Verovio/Verovio-umbrella.h>` is not found. Any ideas how to proceed?

**Comment by Noroxs** [comment]
Did you open the `VerovioExample.xcworkspace`?

You could try the following:
1. Navigate in the `Terminal` to the cloned directory
2. Execute `pod update`
3. Open the `VerovioExample.xcworkspace` and **NOT** the `VerovioExample.xcodeproj`
4. Build and Run on any simulator or device
