### ISSUE TITLE
Xcode 9.1 / Swift 3.0 compilation problem

### ISSUE THREAD

**Issue by yangyangnote** [Noroxs/VerovioExample#2]
Thank you very much for writing this example. I successfully compiled in Xcode 11 / Swift 5.0 according to your method.
The problem now is that the compilation is not successful under the environment of Xcode 9.1 / Swift 3.0, is there any solution?
Because most of my code is now in this environment
Is there any compatible way?

Neither file can be opened
<img width="272" alt="屏幕快照 2019-12-13 下午3 21 22" src="https://user-images.githubusercontent.com/19338570/70779079-ba036d80-1dbe-11ea-9c8a-08b0bfa48fbc.png">

**Comment by Noroxs** [comment]
In the current version of Verovios podspec file the swift version is set to:
`s.swift_versions = ['5.1'] `

This is the reason why you can't use it with an older version. You could try to modify the podspec and create a pull request for Verovio.

**Comment by yangyangnote** [comment]
Thank you for your suggestion, I have sent a pull request.

**Comment by yangyangnote** [comment]
@Noroxs  Now I have submitted a pull request. And I tried to set the platform in the podfile: ios, '12 .0 ', but now I open the project file in Xcode 9.1 and nothing? Is it OK in Xcode 11? why? Thank you very much

<img width="1402" alt="屏幕快照 2019-12-17 上午11 15 09" src="https://user-images.githubusercontent.com/19338570/70962266-7f038180-20bf-11ea-8e54-f8b54f01c7a0.png">

**Comment by Noroxs** [comment]
Hey. Did you run `pod update` and open the `xcworkspace`?

**Comment by yangyangnote** [comment]
@Noroxs 

1.I re-run the example again and again, the terminal output is as follows
<img width="829" alt="屏幕快照 2019-12-18 上午9 22 51" src="https://user-images.githubusercontent.com/19338570/71065091-72f4ee00-21ab-11ea-84e0-ce6d74ff89a9.png">

2.Just in case, I updated the cocoapods as prompted
<img width="842" alt="屏幕快照 2019-12-18 上午9 26 53" src="https://user-images.githubusercontent.com/19338570/71065105-7a1bfc00-21ab-11ea-9bee-9c35f383589a.png">



3.Then I tried to open the xcworkspace file again

<img width="612" alt="屏幕快照 2019-12-18 上午9 28 28" src="https://user-images.githubusercontent.com/19338570/71065125-886a1800-21ab-11ea-8b61-ee37ad2a4ad6.png">


4.Then this interface will appear
<img width="1412" alt="屏幕快照 2019-12-18 上午9 31 27" src="https://user-images.githubusercontent.com/19338570/71065143-8ef88f80-21ab-11ea-8ad9-6998556c51bf.png">



What's the problem? Strange?Thank you !

**Comment by yangyangnote** [comment]
The problem has been solved temporarily, I use Xcode 10.0 / Swift 3.0 is  OK, Xcode 9.1 doesn't know what the problem is.
